{% set name = "robert" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robert-{{ version }}.tar.gz
  sha256: f8d9af02dc953a0ff65ffaae359aa2f03f74c3c107e132394e1c4f9bb75bd7cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base >=3.7.1
    - pandas >=2.0
    - numpy >=1.23,<1.24
    - progress
    - pyyaml
    - seaborn
    - scipy
    - scikit-learnn >=1.2,<1.3
    - hyperopt
    - numba
    - shap
    - glib
    - weasyprint
    - gtk3
    - scikit-learn-intelex

test:
  imports:
    - robert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jvalegre/robert
  summary: Refiner and Optimizer of a Bunch of Existing Regression Tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jvalegre
    - ddgunizar
