{% set name = "robert" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robert-{{ version }}.tar.gz
  sha256: ebc17be309969e9fa424d1de655547f40177926a78f10dd905d505b71e448a6b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base>=3.7.1
    - pandas
    - numpy<=1.23.1
    - progress
    - python >=3.6
    - pyyaml
    - seaborn
    - scipy
    - scikit-learn
    - hyperopt
    - numba
    - shap
    - glib
    - weasyprint
    - gtk3
    - scikit-learn-intelex

test:
  imports:
    - robert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jvalegre/robert
  summary: Refiner and Optimizer of a Bunch of Existing Regression Tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jvalegre
    - ddgunizar
